// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxn4GIrWIRaaK5dzVPwZFGKrFiVK9PXHY',
    appId: '1:984177360287:web:ebe54a5c151b099b9c11aa',
    messagingSenderId: '984177360287',
    projectId: 'technical-friday-prod',
    authDomain: 'technical-friday-prod.firebaseapp.com',
    storageBucket: 'technical-friday-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQBy7rjiKUrNIr4-uNO8IaiD5Z--TgvRU',
    appId: '1:984177360287:android:40b0970b3ca2630c9c11aa',
    messagingSenderId: '984177360287',
    projectId: 'technical-friday-prod',
    storageBucket: 'technical-friday-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtAomT70vT-vD4dKW3IrHOsthfFhMXiJU',
    appId: '1:984177360287:ios:f30a4f56560b57259c11aa',
    messagingSenderId: '984177360287',
    projectId: 'technical-friday-prod',
    storageBucket: 'technical-friday-prod.appspot.com',
    iosClientId: '984177360287-b8j7bpkpq5nm691ovr5lqpt3mp9fht70.apps.googleusercontent.com',
    iosBundleId: 'com.example.technicalFriday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtAomT70vT-vD4dKW3IrHOsthfFhMXiJU',
    appId: '1:984177360287:ios:f30a4f56560b57259c11aa',
    messagingSenderId: '984177360287',
    projectId: 'technical-friday-prod',
    storageBucket: 'technical-friday-prod.appspot.com',
    iosClientId: '984177360287-b8j7bpkpq5nm691ovr5lqpt3mp9fht70.apps.googleusercontent.com',
    iosBundleId: 'com.example.technicalFriday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxn4GIrWIRaaK5dzVPwZFGKrFiVK9PXHY',
    appId: '1:984177360287:web:8fee9889705b01449c11aa',
    messagingSenderId: '984177360287',
    projectId: 'technical-friday-prod',
    authDomain: 'technical-friday-prod.firebaseapp.com',
    storageBucket: 'technical-friday-prod.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAxn4GIrWIRaaK5dzVPwZFGKrFiVK9PXHY',
    appId: '1:984177360287:web:27dacae99f39cc069c11aa',
    messagingSenderId: '984177360287',
    projectId: 'technical-friday-prod',
    authDomain: 'technical-friday-prod.firebaseapp.com',
    storageBucket: 'technical-friday-prod.appspot.com',
  );
}
